### Welcome to the Exercise on TensorFlow 2.x. 

First we make us familiar with linear algebra operations. Then we implement a linear regression model. After that we implement a neural network using the low level TensorFlow API. Finally, we conclude with a neural network implemented in Keras.

Now let's make sure we are on the latest version of TensorFlow

In [1]:
!pip install --upgrade tensorflow

/opt/conda/envs/Python-3.7-main/lib/python3.7/site-packages/secretstorage/dhcrypto.py:16: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/opt/conda/envs/Python-3.7-main/lib/python3.7/site-packages/secretstorage/util.py:25: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
     |████████████████████████████████| 394.3 MB 20 kB/s s eta 0:00:01    |██▋                             | 31.8 MB 10.5 MB/s eta 0:00:35                    | 53.9 MB 8.3 MB/s eta 0:00:42     |███████▏                        | 87.7 MB 10.5 MB/s eta 0:00:30     |███████████████▉                | 194.6 MB 10.8 MB/s eta 0:00:19��▊               | 206.4 MB 10.9 MB/s eta 0:00:18��█               | 209.1 MB 10.9 MB/s eta 0:00:17��█████████████▍              | 214.3 MB 10.9 MB/s eta 0:00:17��█████████████▋              | 217.0 MB 10.9 MB/s eta 0:00:1

In [2]:
import tensorflow as tf
tf.__version__

'2.4.1'

Let's play around with some linear algebra examples

In [3]:
a = tf.constant([1., 2., 2., 3.])
print(a)


b = tf.constant([4., 5., 5., 6.])
print(b)


c = a + b
print(c)

tf.Tensor([1. 2. 2. 3.], shape=(4,), dtype=float32)
tf.Tensor([4. 5. 5. 6.], shape=(4,), dtype=float32)
tf.Tensor([5. 7. 7. 9.], shape=(4,), dtype=float32)


In [4]:
a = tf.constant([1., 2., 2., 3.])
print(a)


b = tf.constant([4., 5., 5., 6.])
print(b)


c = tf.tensordot(a, b, axes=1)
print(c)

tf.Tensor([1. 2. 2. 3.], shape=(4,), dtype=float32)
tf.Tensor([4. 5. 5. 6.], shape=(4,), dtype=float32)
tf.Tensor(42.0, shape=(), dtype=float32)


### Linear Regression

In [5]:
import tensorflow as tf
tf.__version__

import numpy as np
data = np.array(
    [
        [100,35,35,12,0.32],
        [101,46,35,21,0.34],
        [130,56,46,3412,12.42],
        [131,58,48,3542,13.43]
    ]
)

x = data[:,1:-1]
y_target = data[:,-1]

b = tf.Variable(1,dtype=tf.float64)
w = tf.Variable([1,1,1],dtype=tf.float64)


def linear_model(x):
    return b + tf.tensordot(x,w,axes=1)

optimizer = tf.keras.optimizers.Adam()
loss_object = tf.keras.losses.MeanSquaredLogarithmicError()

def train_step(x, y):
    with tf.GradientTape() as tape:
        predicted = linear_model(x)   
        loss_value = loss_object(y, predicted)
        print ('Loss {} '.format(loss_value))
        grads = tape.gradient(loss_value, [b,w])
        optimizer.apply_gradients(zip(grads, [b,w]))
    
def train(epochs):
    for epoch in range(epochs):
            train_step(x, y_target)
    print ('Epoch {} finished'.format(epoch))
    
train(epochs = 1000)


Loss 24.452190399169922 
Loss 24.44243049621582 
Loss 24.432662963867188 
Loss 24.422887802124023 
Loss 24.413103103637695 
Loss 24.403310775756836 
Loss 24.393508911132812 
Loss 24.383699417114258 
Loss 24.37388038635254 
Loss 24.36405372619629 
Loss 24.354217529296875 
Loss 24.344369888305664 
Loss 24.334514617919922 
Loss 24.324649810791016 
Loss 24.314775466918945 
Loss 24.30489158630371 
Loss 24.294998168945312 
Loss 24.285093307495117 
Loss 24.275178909301758 
Loss 24.265254974365234 
Loss 24.255319595336914 
Loss 24.245372772216797 
Loss 24.235416412353516 
Loss 24.22545051574707 
Loss 24.215473175048828 
Loss 24.20548439025879 
Loss 24.195484161376953 
Loss 24.18547248840332 
Loss 24.175451278686523 
Loss 24.16541862487793 
Loss 24.155372619628906 
Loss 24.14531707763672 
Loss 24.1352481842041 
Loss 24.12516975402832 
Loss 24.11507797241211 
Loss 24.1049747467041 
Loss 24.094860076904297 
Loss 24.084733963012695 
Loss 24.074596405029297 
Loss 24.06444549560547 
Loss 24.05428123

In [6]:
b

<tf.Variable 'Variable:0' shape=() dtype=float64, numpy=-0.019146748335402086>

In [7]:
w

<tf.Variable 'Variable:0' shape=(3,) dtype=float64, numpy=array([-0.0120755 , -0.01246163,  0.0040873 ])>

In [8]:
linear_model(x)

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([-0.82889854, -0.92494333, 12.67724995, 13.15952439])>

### Logistic Model

In [9]:
import tensorflow as tf
tf.__version__

import numpy as np


data = np.array(
    [
        [100,35,35,12,0.],
        [101,46,35,21,0.],
        [130,56,46,3412,1.],
        [131,58,48,3542,1.]
    ]
)



x = data[:,1:-1]
y_target = data[:,-1]



x = x / np.linalg.norm(x)

b = tf.Variable(1,dtype=tf.float64)
w = tf.Variable([1,1,1],dtype=tf.float64)


def logstic_model(x):
    return tf.sigmoid(b + tf.tensordot(x,w,axes=1))

optimizer = tf.keras.optimizers.SGD(learning_rate=10)
loss_object = tf.keras.losses.BinaryCrossentropy()

def train_step(x, y):
    with tf.GradientTape() as tape:
        predicted = logstic_model(x) 
        loss_value = loss_object(y, predicted)
        print(loss_value)
        grads = tape.gradient(loss_value, [b,w])
        optimizer.apply_gradients(zip(grads, [b,w]))
    
def train(epochs):
    for epoch in range(epochs):
            train_step(x, y_target)
    
train(epochs = 1000)


tf.Tensor(0.7452549934387207, shape=(), dtype=float64)
tf.Tensor(0.6635751724243164, shape=(), dtype=float64)
tf.Tensor(0.6444340348243713, shape=(), dtype=float64)
tf.Tensor(0.3128647208213806, shape=(), dtype=float64)
tf.Tensor(0.20956075191497803, shape=(), dtype=float64)
tf.Tensor(0.12795603275299072, shape=(), dtype=float64)
tf.Tensor(0.10996071249246597, shape=(), dtype=float64)
tf.Tensor(0.09858797490596771, shape=(), dtype=float64)
tf.Tensor(0.08938299864530563, shape=(), dtype=float64)
tf.Tensor(0.08171940594911575, shape=(), dtype=float64)
tf.Tensor(0.07524453103542328, shape=(), dtype=float64)
tf.Tensor(0.06970474869012833, shape=(), dtype=float64)
tf.Tensor(0.06491319090127945, shape=(), dtype=float64)
tf.Tensor(0.06072930246591568, shape=(), dtype=float64)
tf.Tensor(0.05704540014266968, shape=(), dtype=float64)
tf.Tensor(0.05377765744924545, shape=(), dtype=float64)
tf.Tensor(0.050859883427619934, shape=(), dtype=float64)
tf.Tensor(0.04823913052678108, shape=(), dtype=floa

In [10]:
logstic_model(x)

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([9.97764113e-04, 1.03717093e-03, 9.98973840e-01, 9.99394432e-01])>

### Neural Network

In [11]:
import tensorflow as tf
tf.__version__

import numpy as np
data = np.array(
    [
        [100,35,35,12,0.32],
        [101,46,35,21,0.34],
        [130,56,46,3412,12.42],
        [131,58,48,3542,13.43]
    ]
)

x = data[:,1:-1]
x = x / np.linalg.norm(x)
y_target = data[:,-1]
y_target = y_target / np.linalg.norm(y_target)


w1 = tf.Variable([[1,1,1],[1,1,1],[1,1,1]],dtype=tf.float64)
w2 = tf.Variable([1,1,1],dtype=tf.float64)

def layer1(x):
    return tf.sigmoid(tf.tensordot(x,w1,axes=1))

print(layer1(x))

def layer2(x):
    return tf.sigmoid(tf.tensordot(layer1(x),w2,axes=1))



optimizer = tf.keras.optimizers.Adam(learning_rate=0.01)
loss_object = tf.keras.losses.MeanSquaredLogarithmicError()

def train_step(x, y):
    with tf.GradientTape() as tape:
        predicted = layer2(x)   
        loss_value = loss_object(y, predicted)
        print(loss_value)
        grads = tape.gradient(loss_value, [w1,w2])
        optimizer.apply_gradients(zip(grads, [w1,w2]))
    
def train(epochs):
    for epoch in range(epochs):
            train_step(x, y_target)
    print ('Epoch {} finished'.format(epoch))
    
train(epochs = 1000)



tf.Tensor(
[[0.50416671 0.50416671 0.50416671]
 [0.50518291 0.50518291 0.50518291]
 [0.67133984 0.67133984 0.67133984]
 [0.67732112 0.67732112 0.67732112]], shape=(4, 3), dtype=float64)
tf.Tensor(0.17364807426929474, shape=(), dtype=float64)
tf.Tensor(0.1727887988090515, shape=(), dtype=float64)
tf.Tensor(0.17192263901233673, shape=(), dtype=float64)
tf.Tensor(0.17104960978031158, shape=(), dtype=float64)
tf.Tensor(0.17016975581645966, shape=(), dtype=float64)
tf.Tensor(0.16928307712078094, shape=(), dtype=float64)
tf.Tensor(0.16838957369327545, shape=(), dtype=float64)
tf.Tensor(0.16748927533626556, shape=(), dtype=float64)
tf.Tensor(0.16658221185207367, shape=(), dtype=float64)
tf.Tensor(0.16566839814186096, shape=(), dtype=float64)
tf.Tensor(0.1647479087114334, shape=(), dtype=float64)
tf.Tensor(0.1638207733631134, shape=(), dtype=float64)
tf.Tensor(0.16288705170154572, shape=(), dtype=float64)
tf.Tensor(0.1619468480348587, shape=(), dtype=float64)
tf.Tensor(0.16100022196769714, sha

In [12]:
w1 

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float64, numpy=
array([[ 0.44021805,  0.44021805,  0.44021805],
       [ 0.70261531,  0.70261531,  0.70261531],
       [-6.3130148 , -6.3130148 , -6.3130148 ]])>

In [13]:
layer1(x)

<tf.Tensor: shape=(4, 3), dtype=float64, numpy=
array([[0.49818303, 0.49818303, 0.49818303],
       [0.49554206, 0.49554206, 0.49554206],
       [0.01253503, 0.01253503, 0.01253503],
       [0.01063448, 0.01063448, 0.01063448]])>

In [14]:
x

array([[0.00711406, 0.00711406, 0.0024391 ],
       [0.0093499 , 0.00711406, 0.00426843],
       [0.01138249, 0.0093499 , 0.6935188 ],
       [0.01178901, 0.00975642, 0.71994243]])

### Keras

In [15]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD
from tensorflow.keras.utils import to_categorical

data = np.array(
    [
        [100,35,35,12,0],
        [101,46,35,21,0],
        [130,56,46,3412,1],
        [131,58,48,3542,1]
    ]
)

x = data[:,1:-1]
y_target = data[:,-1]

x = x / np.linalg.norm(x)

model = Sequential()
model.add(Dense(3, input_shape=(3,), activation='sigmoid'))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer=SGD(learning_rate=0.1),
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(x, y_target, epochs=1000,
          verbose=1)

Epoch 1/1000
1/1 [==============================] - 1s 550ms/step - loss: 0.7139 - accuracy: 0.5000
Epoch 2/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.7108 - accuracy: 0.5000
Epoch 3/1000
1/1 [==============================] - 0s 13ms/step - loss: 0.7079 - accuracy: 0.5000
Epoch 4/1000
1/1 [==============================] - 0s 18ms/step - loss: 0.7052 - accuracy: 0.5000
Epoch 5/1000
1/1 [==============================] - 0s 16ms/step - loss: 0.7027 - accuracy: 0.5000
Epoch 6/1000
1/1 [==============================] - 0s 17ms/step - loss: 0.7004 - accuracy: 0.5000
Epoch 7/1000
1/1 [==============================] - 0s 15ms/step - loss: 0.6983 - accuracy: 0.5000
Epoch 8/1000
1/1 [==============================] - 0s 18ms/step - loss: 0.6963 - accuracy: 0.5000
Epoch 9/1000
1/1 [==============================] - 0s 17ms/step - loss: 0.6945 - accuracy: 0.5000
Epoch 10/1000
1/1 [==============================] - 0s 5ms/step - loss: 0.6928 - accuracy: 0.5000
Epoch 11/1

In [16]:
model.predict(x)

array([[0.07175195],
       [0.0724414 ],
       [0.9286715 ],
       [0.9373475 ]], dtype=float32)